Minimum system work

diff --git a/ncurses-ada/ncurses-ada.SlackBuild b/ncurses-ada/ncurses-ada.SlackBuild
--- a/ncurses-ada/ncurses-ada.SlackBuild
+++ b/ncurses-ada/ncurses-ada.SlackBuild
@@ -1,6 +1,7 @@
-#!/bin/sh
+#!/bin/bash
 
-# Copyright 2000-2011, 2013, 2014, 2015, 2016, 2017  Patrick J. Volkerding, Sebeka, MN, USA
+# Copyright 2021 Zhu Qun-Ying
+# Copyright 2000-2011, 2013, 2014, 2015, 2016, 2017, 2018, 2019  Patrick J. Volkerding, Sebeka, MN, USA
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -20,11 +21,14 @@
 #  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 #  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-PRGNAM=ncurses
-VERSION=${VERSION:-$(echo $PRGNAM-*.tar.?z | rev | cut -f 3- -d . | cut -f 1 -d - | rev)}
-BUILD=${BUILD:-1}
+cd $(dirname $0) ; CWD=$(pwd)
 
 PKGNAM=ncurses-ada
+SRCNAM=ncurses
+VERSION=${VERSION:-$(echo $SRCNAM-*.tar.?z | cut -f 2- -d - | cut -f 1,2 -d .)}
+BUILD=${BUILD:-1}
+TAG=${TAG:-_sAda}
+
 # Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -35,9 +39,19 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-CWD=$(pwd)
-TMP=${TMP:-/tmp}
+# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
+# the name of the created package would be, and then exit. This information
+# could be useful to other scripts.
+if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
+  echo "$PKGNAM-$(echo $VERSION | tr - _)-$ARCH-$BUILD.txz"
+  exit 0
+fi
+
+NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
+
+TMP=${TMP:-/tmp/slackAda}
 PKG=$TMP/package-$PKGNAM
+OUTPUT=${OUTPUT:-/tmp}
 
 if [ "$ARCH" = "i586" ]; then
   SLKCFLAGS="-O2 -march=i586 -mtune=i686"
@@ -72,6 +86,7 @@ CFLAGS="$SLKCFLAGS" \
   --with-shared \
   --without-debug \
   --disable-static \
+  --without-normal \
   --without-profile \
   --enable-symlinks \
   --enable-pc-files \
@@ -93,28 +108,35 @@ tar xvf $CWD/ncurses-$VERSION.tar.?z || exit 1
 cd ncurses-$VERSION || exit 1
 chown -R root:root .
 
-# Apply upstream patch collection:
-xzcat $CWD/ncurses-6.0-20160910-patch.sh.xz > ncurses-6.0-20160910-patch.sh
-sh ncurses-6.0-20160910-patch.sh
+## NOTE: nevermind trying this... patches have multiple failures. Use the
+## dated archive from upstream instead.
+#
+### No rollup (*.patch.sh) patch available yet for ncurses-6.1, so we'll
+### comment this out for now.
+## Apply upstream patch collection:
+#xzcat $CWD/ncurses-6.0-20160910-patch.sh.xz > ncurses-6.0-20160910-patch.sh
+#sh ncurses-6.0-20160910-patch.sh
+## Apply weekly ncurses patch updates:
+#for file in $CWD/patches/*.patch.gz ; do
+#  zcat $file | patch -p1 --verbose || exit 1
+#done
 
 zcat $CWD/ncurses.mkhashsize.diff.gz | patch -p1 --verbose || exit 1
 
 ADA_SUPPORT="--with-ada-include=/usr/include/ncurses-ada \
  --with-ada-objects=/usr/lib$LIBDIRSUFFIX/ncurses-ada"
-ncurses_configure
-make -j4 || exit 1
-# Install the package:
-make install DESTDIR=$PKG
+ncurses_configure || exit 1
+make $NUMJOBS || exit 1
+make install DESTDIR=$PKG || exit 1
 
-# Build/install again with wide character support:
+# Configure/build/install again with wide character support:
 make clean
 WIDEC=--enable-widec
 ADA_SUPPORT="--with-ada-include=/usr/include/ncursesw-ada \
  --with-ada-objects=/usr/lib$LIBDIRSUFFIX/ncursesw-ada"
-ncurses_configure
-make -j4 || exit 1
-make install
-make install DESTDIR=$PKG
+ncurses_configure || exit 1
+make $NUMJOBS || exit 1
+make install DESTDIR=$PKG || exit 1
 
 # remove all non ada files
 # Remove all C libs
@@ -132,18 +154,19 @@ ls | grep -v ada | xargs rm)
 
 # Then, add /usr/doc/ncurses-xxxxx with appropriate files.
 mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION
+cp -a doc/html $PKG/usr/doc/$PKGNAM-$VERSION
 cp -a Ada95/samples $PKG/usr/doc/$PKGNAM-$VERSION
-(cd  $PKG/usr/doc/$PKGNAM-$VERSION; rm *.ali *.o)
+(cd  $PKG/usr/doc/$PKGNAM-$VERSION/samples; rm *.ali *.o)
 
 #Copy Ada project files
 mkdir -p $PKG/usr/lib$LIBDIRSUFFIX/gnat
-cp $CWD/ncurses.gpr $PKG/usr/lib$LIBDIRSUFFIX/gnat
-cp $CWD/ncursesw.gpr $PKG/usr/lib$LIBDIRSUFFIX/gnat
+sed "s/%lib_dir%/lib$LIBDIRSUFFIX/" $CWD/ncurses.gpr > $PKG/usr/share/gpr/ncurses.gpr
+sed "s/%lib_dir%/lib$LIBDIRSUFFIX/" $CWD/ncursesw.gpr > $PKG/usr/share/gpr/ncursesw.gpr
 
 # desc file:
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-/sbin/makepkg -l y -c n $TMP/$PKGNAM-$VERSION-$ARCH-$BUILD.txz
+/sbin/makepkg -l y -c n $OUTPUT/$PKGNAM-$(echo $VERSION | tr - _)-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
 
